Repository ucsb-cs156-w24/proj-courses-w24-5pm-2, pull requests merged in 2024-03, with the labels that each got.

#16 FEATURE: Add link to developer/GH info in Admin dropdown
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/tests/components/Nav/AppNavbar.test.js
Labels: 5 points

#17 BUG: Can't immediately search for graduate courses
  frontend/src/main/components/BasicCourseSearch/BasicCourseSearchForm.js
  frontend/src/tests/components/Levels/SingleLevelDropdown.test.js
Labels: 10 points

#18 BUG: Deleting a personal schedule doesn't delete associated PSCourses
  src/main/java/edu/ucsb/cs156/courses/controllers/PersonalSchedulesController.java
  src/test/java/edu/ucsb/cs156/courses/controllers/PersonalSchedulesControllerTests.java
Labels: 20 points

#19 FEATURE: More descriptive error message on personal schedule with Bonus
  frontend/src/main/pages/Courses/PSCourseCreatePage.js
  frontend/src/tests/pages/Courses/CoursesCreatePage.test.js
Labels: 10 points

#21 BUG: Fixes Local Schedule Storage Bug
  frontend/src/main/components/Courses/CourseForm.js
Labels: 5 points

#22 REFACTOR: Simplify "Personal schedule" navigation
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/pages/Courses/PSCourseIndexPage.js
  frontend/src/main/pages/PersonalSchedules/PersonalSchedulesDetailsPage.js
  frontend/src/main/pages/PersonalSchedules/PersonalSchedulesEditPage.js
  frontend/src/main/pages/PersonalSchedules/PersonalSchedulesIndexPage.js
  frontend/src/tests/components/Nav/AppNavbar.test.js
  frontend/src/tests/pages/Courses/CoursesIndexPage.test.js
  frontend/src/tests/pages/PersonalSchedules/PersonalSchedulesDetailsPage.test.js
  frontend/src/tests/pages/PersonalSchedules/PersonalSchedulesEditPage.test.js
  frontend/src/tests/pages/PersonalSchedules/PersonalSchedulesIndexPage.test.js
Labels: 5 points, 10 points, merge candidate

#25 Add frontend for job to update all courses in a range of quarters
  frontend/src/main/components/Jobs/UpdateCoursesByQuarterRangeJobForm.js
  frontend/src/main/pages/AdminJobsPage.js
  frontend/src/stories/components/Jobs/UpdateCoursesByQuarterRangeJobForm.stories.js
  frontend/src/tests/components/Jobs/UpdateCoursesByQuarterRangeJobForm.test.js
  frontend/src/tests/pages/AdminJobsPage.test.js
Labels: 10 points, merge candidate

#27 Jh Add Course From Search
  frontend/src/main/components/PersonalSchedules/AddToScheduleModal.js
  frontend/src/main/components/PersonalSchedules/PersonalScheduleSelector.js
  frontend/src/main/components/Sections/SectionsTable.js
  frontend/src/tests/components/PersonalSchedules/AddToScheduleModal.test.js
  frontend/src/tests/components/PersonalSchedules/PersonalScheduleSelector.test.js
  frontend/src/tests/components/Sections/SectionsTable.test.js
Labels: 20 points

#24 FEATURE: Add edit page for personal schedules
  frontend/src/main/components/PersonalSchedules/PersonalScheduleForm.js
  frontend/src/main/components/Quarters/SingleQuarterDropdown.js
  frontend/src/main/pages/PersonalSchedules/PersonalSchedulesEditPage.js
  frontend/src/stories/pages/PersonalSchedulesEditPage.stories.js
  frontend/src/tests/components/PersonalSchedules/PersonalScheduleForm.test.js
  frontend/src/tests/pages/PersonalSchedules/PersonalSchedulesEditPage.test.js
Labels: 20 points
